name: DNS Tester

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点（北京时间 8 点）定时运行
  workflow_dispatch:  # 支持手动触发

jobs:
  dns-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Print working directory contents
        run: |
          echo "Current working directory contents:"
          ls -R
          echo "Path to check-ip directory:"
          ls -R check-ip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f check-ip/requirements.txt ]; then
            pip install -r check-ip/requirements.txt
          else
            echo "requirements.txt not found. Skipping dependency installation."
          fi

      - name: Run DNS tester
        run: python check-ip/dns_tester.py

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: dns-test-results
          path: check-ip/results

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add check-ip/results
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update DNS test results"
            git push
          fi
