name: DNS Tester

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点（北京时间 8 点）定时运行
  workflow_dispatch:  # 支持手动触发

jobs:
  dns-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Print working directory contents
        run: |
          echo "Current working directory contents:"
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Skipping dependency installation."
          fi

      - name: Run DNS tester
        run: python dns_tester.py

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: dns-test-results
          path: results

      - name: Commit and push results to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update DNS test results"
            git push
          fi

      - name: Checkout or create 'page' branch
        run: |
          git fetch origin page
          if git show-ref --verify --quiet refs/heads/page; then
            git checkout page
          else
            git checkout -b page
          fi

      - name: Copy index.html to 'page' branch
        run: |
          cp results/index.html .
          git add index.html
          if git diff --staged --quiet; then
            echo "No changes to commit in 'page' branch."
          else
            git commit -m "Update index.html in 'page' branch"
            git push origin page
          fi
